/** table mapped class in model/entity
 * the model/entity holds all "JPA entities"-classes that map to database tables
 * *****So Task.java = an Entity(a row in the DB table)*****
 * The physical table(in H2/MySQL) is auto-generated by JPA/Hibernate^ based on this class
 * ***Table is not inside the code, it is generated in your database automatically.
 * The model pakage holds the definirtion/blueprints for that Table.
 */
package com.example.taskmanager.model;

import jakarta.persistence.*; //import JPA annotations
import lombok.*; //lombok removes the need to write boilerplate

@Entity // Tells JPA that this class representes a database table
@Data // Gernerates Getters,Setters, toString(), equals(), hashCode().
@NoArgsConstructor // default constructor- new Task();
@AllArgsConstructor // Task(Long id, String title, boolean completed)
@Builder // Lets u fill any field(id/title/completed) in any order
public class Task {
    @Id // Marks the Primary key column
    // Primary key ~ sl.no. Unique identifier for each row
    @GeneratedValue(strategy = GenerationType.IDENTITY) // tells database to autogenerate primary key^^
    //all primitive for encapsulation, u can set rules or validation 
    //eg in setter u can set if id>0 this.id =id
    //Long-wrapper class obj as JPA needs object to set field = null
    private Long id;
    private String title;
    private boolean completed;

}
/**
 * ^^when you add a new task:
 * {"title": "Learn Spring boot", "completed": true}, database automatically
 * gives it an id:
 * {"id"; 1, "title": "Learn Spring boot", "completed": true}
 * 
 * 
 * ^JPA (Java Persistence API) is a specification for managing relational data
 * in Java applications. It defines a standard way to map Java objects
 * (entities) to relational database tables and perform database operations
 * (CRUD - Create, Read, Update, Delete) on them. JPA aims to simplify database
 * interactions by abstracting away the underlying SQL and JDBC complexities,
 * allowing developers to work with Java objects.
 * 
 * Hibernate is a popular implementation of the JPA specification. It is an
 * Object-Relational Mapping (ORM) framework that provides the actual engine to
 * perform the mapping and persistence operations defined by JPA.
 * 
 * In essence, JPA provides the blueprint and standard API for persistence in
 * Java, while Hibernate is a concrete tool that brings that blueprint to life,
 * offering a robust and feature-rich solution for object-relational mapping.
 * When working with JPA, you are often using an underlying JPA provider like
 * Hibernate to handle the actual database interactions.
 */